# Generated by Django 2.1.2 on 2018-11-26 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
