# Generated by Django 2.1.2 on 2018-11-26 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
