# Generated by Django 2.1.2 on 2018-12-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0005_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
