# Generated by Django 2.1.2 on 2018-12-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0009_auto_20181209_0347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profilepics'),
        ),
    ]
