# Generated by Django 2.1.2 on 2018-12-19 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0010_auto_20181209_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=500)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('content', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profilepics/default1.jpg', upload_to='profilepics'),
        ),
        migrations.AddField(
            model_name='postsubmission',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creo.UserProfileInfo'),
        ),
    ]
