# Generated by Django 2.1.2 on 2018-12-19 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0012_auto_20181219_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubmission',
            name='content',
            field=models.ImageField(blank=True, upload_to='postedpics'),
        ),
    ]
