# Generated by Django 2.1.2 on 2018-12-20 00:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0013_auto_20181219_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubmission',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
