# Generated by Django 2.1.2 on 2018-12-27 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0014_auto_20181220_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='creo.PostSubmission')),
            ],
        ),
    ]
