# Generated by Django 2.1.2 on 2018-12-27 09:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0016_auto_20181227_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentpost',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
