# Generated by Django 2.1.2 on 2018-12-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0019_commentpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubmission',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
