# Generated by Django 2.1.2 on 2018-12-27 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0020_postsubmission_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubmission',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
