# Generated by Django 2.1.2 on 2019-01-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0028_auto_20190103_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubmission',
            name='content',
            field=models.FileField(blank=True, upload_to='posts'),
        ),
    ]
