# Generated by Django 2.1.2 on 2019-01-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0030_userprofileinfo_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubmission',
            name='post_type',
            field=models.CharField(blank=True, choices=[(0, 'Image'), (1, 'Video'), (2, 'Audio')], default=0, max_length=12),
        ),
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=12),
        ),
    ]
