# Generated by Django 2.1.2 on 2019-01-04 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0031_auto_20190104_0330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsubmission',
            name='post_type',
            field=models.CharField(choices=[(0, 'Image'), (1, 'Video'), (2, 'Audio')], max_length=12),
        ),
    ]
