# Generated by Django 2.1.2 on 2019-01-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0032_auto_20190104_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileinfo',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=12),
        ),
    ]
