# Generated by Django 2.1.2 on 2019-01-04 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0033_auto_20190104_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsubmission',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='postsubmission',
            name='image',
        ),
        migrations.RemoveField(
            model_name='postsubmission',
            name='video',
        ),
    ]
