# Generated by Django 2.1.2 on 2019-01-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0034_auto_20190104_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofileinfo',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofileinfo',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
    ]
