# Generated by Django 2.1.2 on 2019-01-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0035_auto_20190104_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsubmission',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
