# Generated by Django 2.1.5 on 2019-01-07 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0036_postsubmission_view_count'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testers',
        ),
    ]
