# Generated by Django 2.1.2 on 2019-01-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('creo', '0039_savedpost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedpost',
            old_name='save',
            new_name='save_post',
        ),
    ]
